create table if not exists order_basket
(
    id      varchar unique,
    fio     varchar not null,
    address varchar not null,
    primary key (id)
);

create table if not exists order_product
(
    id              varchar unique,
    title           varchar not null,
    building_id     int     not null,
    order_basket_id varchar references order_basket (id) on DELETE cascade,
    primary key (id)
);

create table if not exists order_product_ingredient
(
    id               int generated by default as identity unique,
    title            varchar not null,
    weight           int     not null,
    order_product_id varchar references order_product (id) on delete cascade,
    primary key (id)
);