create table if not exists building
(
    id              int generated by default as identity,
    name            varchar,
    is_new_delivery varchar default 'FALSE',
    primary key (id)
);

create table if not exists warehouse
(
    id          int generated by default as identity,
    title       varchar,
    weight      int,
    building_id int references building (id),
    primary key (id)
);

create table if not exists new_delivery
(
    building_id     int references building (id),
    is_new_delivery varchar default 'FALSE',
    primary key (building_id)
);

create table if not exists new_delivery_basket
(
    id          varchar,
    building_id int references new_delivery (building_id),
    primary key (id)
);

create table if not exists new_delivery_ingredients
(
    id          int generated by default as identity,
    title       varchar,
    weight      int,
    status      varchar,
    building_id int,
    basket_id   varchar references new_delivery_basket (id),
    primary key (id)
);