server:
  port: 8085

spring:
  application:
    name: restaurant
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/restaurant;MODE=PostgreSQL;
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      data-locations: classpath:db/scripts/data/import_*_data.sql
  liquibase:
    change-log: classpath:db/migrations/h2-changeLog.xml

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: Dimik2001.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migrations/postgres-changeLog.xml