server:
  port: 8085

spring:
  application:
    name: restaurant
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:/static/scripts/schema/import_*_schema.sql
      data-locations: classpath:/static/scripts/data/import_*_data.sql

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: Dimik2001.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect