create table order_basket
(
    id      varchar primary key,
    fio     varchar not null,
    address varchar not null
);
create table order_product
(
    id              varchar primary key,
    title           varchar not null,
    building_id     int     not null,
    order_basket_id varchar references order_basket (id) on DELETE cascade
);
create table order_product_ingredient
(
    id               int primary key generated by default as identity,
    title            varchar not null,
    weight           int     not null,
    order_product_id varchar references order_product (id) on delete cascade
);