create table new_delivery
(
    id int primary key references building (id),
    is_new_delivery varchar default 'FALSE'
);
insert into new_delivery(id)    values (1);
insert into new_delivery(id)    values (2);
insert into new_delivery(id)    values (3);
insert into new_delivery(id)    values (4);
insert into new_delivery(id)    values (5);

create table new_delivery_ingredients
(
    id          int primary key generated by default as identity,
    title       varchar,
    weight      int,
    status      varchar,
    building_id int,
    basket_id varchar references new_delivery_basket(id)
);

truncate new_delivery_ingredients;
truncate new_delivery_basket cascade;
update new_delivery set is_new_delivery = 'FALSE' where id=1;
update new_delivery set is_new_delivery = 'FALSE' where id=2;
update new_delivery set is_new_delivery = 'FALSE' where id=3;
update new_delivery set is_new_delivery = 'FALSE' where id=4;
update new_delivery set is_new_delivery = 'FALSE' where id=5;


create table new_delivery_basket(
    id varchar primary key,
    new_delivery_id int references new_delivery(id)
);

drop table new_delivery_ingredients;
drop table new_delivery_basket;